# Site settings
title: Hillsborough Hack-a-Thon

email: your-email@domain.com

description: >
  A different kind of competition is heating up in Hillsborough County as designers, developers and tech entrepreneurs face-off in Hillsborough County’s Hack-A-Thon.

event_date: "Saturday, June 6, 2015"

baseurl: "/hackathon" # the subpath of your site, e.g. /blog/
url: "http://hackhillsborough.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
